### ISSUE TITLE
Suggestion: Change H1 Color

### ISSUE THREAD

**Issue by ismaelgonzalez** [EM-ismaelgonzalez/github-actions-test#1]
I think the title color looks better if its a different shade of orange

```css
h1 {
  color: #efa82e;
}
```
